# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d236b8312d0227a9a7e6f6429f52509cf61bed1b5476b313edc9b5ba8594f56799ab991e1890cb4ffe60cabe9881995693dc6479aa814a700ccf93745792d2e3

test:
  secret_key_base: e0d21158b4fdca66605c53d4eac8ac458430252a21211aa2450114f7c2b1ba50350ed4a6723f67a352d9d77a7b04a1a37c45f778c8328145cc97f474b608fc88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
